# Generated by Django 5.2.9 on 2025-12-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='送信元メールアドレス（例: noreply@salesmind.mind-bridge.tech）', max_length=254, unique=True)),
                ('name', models.CharField(help_text='表示名（例: SalesMind サポート）', max_length=100)),
                ('purpose', models.CharField(choices=[('default', 'デフォルト（その他）'), ('registration', '会員登録確認'), ('password_reset', 'パスワードリセット'), ('notification', '通知'), ('support', 'サポート'), ('marketing', 'マーケティング'), ('system', 'システム通知')], default='default', help_text='メール送信の用途', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('is_default', models.BooleanField(default=False, help_text='デフォルト送信元として使用')),
                ('description', models.TextField(blank=True, help_text='説明・用途メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'システムメールアドレス',
                'verbose_name_plural': 'システムメールアドレス',
                'ordering': ['-is_default', 'purpose', 'email'],
            },
        ),
    ]
