# Generated by Django 5.2.9 on 2025-12-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systememailaddress',
            table='spin_systememailaddress',
        ),
    ]
