# Generated by Django 5.2.9 on 2025-12-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_alter_systememailaddress_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='テンプレート名（例: registration_email）', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='表示名（例: 会員登録確認メール）', max_length=200)),
                ('purpose', models.CharField(choices=[('registration', '会員登録確認'), ('password_reset', 'パスワードリセット'), ('notification', '通知'), ('welcome', 'ウェルカムメール'), ('other', 'その他')], default='other', help_text='メールの用途', max_length=50)),
                ('subject', models.CharField(help_text='件名（変数使用可: {username}, {site_name}等）', max_length=200)),
                ('body_text', models.TextField(help_text='本文（テキスト版）\n変数使用可: {username}, {verification_url}, {site_name}等')),
                ('body_html', models.TextField(blank=True, help_text='本文（HTML版・オプション）\n変数使用可: {username}, {verification_url}, {site_name}等')),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('available_variables', models.TextField(blank=True, help_text='利用可能な変数のリスト（参考用、カンマ区切り）\n例: username, email, verification_url, site_name')),
                ('description', models.TextField(blank=True, help_text='説明・用途メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.ForeignKey(blank=True, help_text='送信元メールアドレス（空欄の場合はデフォルトを使用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='email_management.systememailaddress')),
            ],
            options={
                'verbose_name': 'メールテンプレート',
                'verbose_name_plural': 'メールテンプレート',
                'db_table': 'email_management_emailtemplate',
                'ordering': ['purpose', 'name'],
            },
        ),
    ]
