# Generated by Django 5.2.7 on 2025-11-03 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="スクレイピング元URL（単一URL or sitemap.xml URL）",
                        max_length=500,
                    ),
                ),
                (
                    "scrape_source",
                    models.CharField(
                        choices=[("url", "単一URL"), ("sitemap", "sitemap.xml")],
                        default="url",
                        max_length=20,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("business_description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "employee_count",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("established_year", models.IntegerField(blank=True, null=True)),
                (
                    "scraped_urls",
                    models.JSONField(
                        blank=True,
                        help_text="スクレイピングしたURL一覧（sitemap.xmlの場合）",
                        null=True,
                    ),
                ),
                (
                    "scraped_data",
                    models.JSONField(
                        blank=True,
                        help_text="生データ保存（複数URLのデータを統合）",
                        null=True,
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "企業情報",
                "verbose_name_plural": "企業情報",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="企業情報との関連付け",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="spin.company",
            ),
        ),
        migrations.CreateModel(
            name="CompanyAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value_proposition",
                    models.TextField(help_text="ユーザーが提案する価値提案"),
                ),
                ("spin_suitability", models.JSONField(help_text="SPIN適合性スコア")),
                (
                    "recommendations",
                    models.JSONField(blank=True, help_text="提案推奨事項", null=True),
                ),
                (
                    "analysis_details",
                    models.JSONField(blank=True, help_text="詳細分析結果", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="spin.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "企業分析結果",
                "verbose_name_plural": "企業分析結果",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="company_analysis",
            field=models.ForeignKey(
                blank=True,
                help_text="分析結果との関連付け",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="spin.companyanalysis",
            ),
        ),
    ]
