# Generated by Django 5.2.7 on 2025-11-03 08:56

from django.db import migrations, models


def set_mode_from_company(apps, schema_editor):
    """既存セッションのmodeをcompanyの有無で設定"""
    Session = apps.get_model('spin', 'Session')
    
    # companyがある場合は詳細診断モード
    Session.objects.filter(company__isnull=False).update(mode='detailed')
    
    # companyがない場合は簡易診断モード
    Session.objects.filter(company__isnull=True).update(mode='simple')
    
    # 整合性チェック（念のため）
    detailed_without_company = Session.objects.filter(mode='detailed', company__isnull=True).count()
    simple_with_company = Session.objects.filter(mode='simple', company__isnull=False).count()
    
    if detailed_without_company > 0 or simple_with_company > 0:
        raise ValueError(f"データ整合性エラー: detailed_without_company={detailed_without_company}, simple_with_company={simple_with_company}")


def reverse_set_mode_from_company(apps, schema_editor):
    """ロールバック時は何もしない（フィールドを削除するだけ）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0002_company_session_company_companyanalysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="mode",
            field=models.CharField(
                choices=[("simple", "簡易診断"), ("detailed", "詳細診断")],
                default="simple",
                help_text="診断モード（簡易診断または詳細診断）",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_mode_from_company, reverse_set_mode_from_company),
    ]
