# Generated by Django 5.2.7 on 2025-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0005_chatmessage_spin_stage_chatmessage_stage_evaluation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="closing_action",
            field=models.CharField(
                blank=True,
                help_text="クロージング提案の種類（見積/デモ/資料/日程調整）",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="conversation_phase",
            field=models.CharField(
                choices=[
                    ("SPIN_S", "SPIN - 状況確認"),
                    ("SPIN_P", "SPIN - 課題顕在化"),
                    ("SPIN_I", "SPIN - 示唆"),
                    ("SPIN_N", "SPIN - 解決メリット"),
                    ("CLOSING_READY", "クロージング準備完了"),
                    ("CLOSING_ACTION", "クロージング実行中"),
                ],
                default="SPIN_S",
                help_text="会話フェーズ（SPIN段階またはクロージング段階）",
                max_length=20,
            ),
        ),
    ]
