# Generated by Django 5.2.7 on 2025-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0006_add_conversation_phase_and_closing"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="loss_reason",
            field=models.CharField(
                blank=True,
                help_text="失注理由（予算不足、タイミング、必要性など）",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="conversation_phase",
            field=models.CharField(
                choices=[
                    ("SPIN_S", "SPIN - 状況確認"),
                    ("SPIN_P", "SPIN - 課題顕在化"),
                    ("SPIN_I", "SPIN - 示唆"),
                    ("SPIN_N", "SPIN - 解決メリット"),
                    ("CLOSING_READY", "クロージング準備完了"),
                    ("CLOSING_ACTION", "クロージング実行中"),
                    ("LOSS_CANDIDATE", "失注候補"),
                    ("LOSS_CONFIRMED", "失注確定"),
                ],
                default="SPIN_S",
                help_text="会話フェーズ（SPIN段階、クロージング段階、または失注段階）",
                max_length=20,
            ),
        ),
    ]
