# Generated by Django 5.2.7 on 2025-11-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0007_add_loss_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="temperature_details",
            field=models.JSONField(
                blank=True,
                help_text="温度スコアの詳細情報（sentiment, buying_signal, cognitive_load, engagement, question_score）",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="temperature_score",
            field=models.FloatField(
                blank=True, help_text="顧客温度スコア（0〜100）", null=True
            ),
        ),
    ]
