# Generated by Django 5.2.8 on 2025-12-02 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0008_add_temperature_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='キーの識別名（例: 本番用、テスト用）', max_length=200)),
                ('api_key', models.CharField(help_text='OpenAI APIキー', max_length=500)),
                ('purpose', models.CharField(choices=[('spin_generation', 'SPIN質問生成'), ('chat', 'チャット（顧客役）'), ('scoring', 'スコアリング'), ('scraping_analysis', 'スクレイピング分析'), ('general', '汎用')], default='general', help_text='APIキーの用途', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('is_default', models.BooleanField(default=False, help_text='デフォルトキー')),
                ('description', models.TextField(blank=True, help_text='キーの説明', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI APIキー',
                'verbose_name_plural': 'OpenAI APIキー',
                'ordering': ['-is_default', '-is_active', '-created_at'],
            },
        ),
    ]
