# Generated by Django 5.2.8 on 2025-12-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0009_openaiapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiapikey',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o（最新・高性能）'), ('gpt-4o-mini', 'GPT-4o-mini（高速・低コスト）'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o-mini', help_text='使用するOpenAIモデル', max_length=50),
        ),
    ]
