# Generated by Django 5.2.8 on 2025-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0010_add_model_name_to_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapikey',
            name='model_name',
            field=models.CharField(choices=[('gpt-5.2', 'GPT-5.2（最新・最高性能・推論能力強化）'), ('gpt-5.1', 'GPT-5.1（高性能・推論能力）'), ('gpt-4o', 'GPT-4o（高性能）'), ('gpt-4o-mini', 'GPT-4o-mini（高速・低コスト）'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo（レガシー）')], default='gpt-4o-mini', help_text='使用するOpenAIモデル', max_length=50),
        ),
    ]
