# Generated by Django 5.2.8 on 2025-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0011_update_model_choices_gpt5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('spin_generation', 'SPIN質問生成'), ('chat', 'チャット（顧客役）'), ('scoring', 'スコアリング'), ('scraping_analysis', 'スクレイピング分析')], help_text='用途', max_length=50, unique=True)),
                ('model_name', models.CharField(choices=[('gpt-5.2', 'GPT-5.2（最新・最高性能・推論能力強化）'), ('gpt-5.1', 'GPT-5.1（高性能・推論能力）'), ('gpt-4o', 'GPT-4o（高性能）'), ('gpt-4o-mini', 'GPT-4o-mini（高速・低コスト）'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo（レガシー）')], help_text='使用するモデル', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='この設定を有効にする')),
                ('notes', models.TextField(blank=True, help_text='メモ・備考', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'モデル設定',
                'verbose_name_plural': 'モデル設定',
                'ordering': ['purpose'],
            },
        ),
    ]
