# Generated by Django 5.2.8 on 2025-12-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0012_add_model_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openaiapikey',
            options={'ordering': ['-is_default', '-is_active', '-created_at'], 'verbose_name': 'APIキー管理', 'verbose_name_plural': 'APIキー管理'},
        ),
    ]
