# Generated by Django 5.2.8 on 2025-12-18 08:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0013_alter_openaiapikey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='キーの識別名（例: Main OpenAI API, Claude Backup）', max_length=200)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('other', 'その他')], default='openai', help_text='AIプロバイダー', max_length=50)),
                ('api_key', models.CharField(help_text='APIキー', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text='カスタムAPIエンドポイント（オプション）', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='キーの説明', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('is_default', models.BooleanField(default=False, help_text='このプロバイダーのデフォルトキー')),
                ('rate_limit_rpm', models.IntegerField(blank=True, help_text='レート制限（Requests Per Minute）', null=True)),
                ('rate_limit_tpm', models.IntegerField(blank=True, help_text='レート制限（Tokens Per Minute）', null=True)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, help_text='月間予算上限（USD）', max_digits=10, null=True)),
                ('current_usage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='当月の使用量（USD）', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'APIキー',
                'verbose_name_plural': 'APIキー',
                'ordering': ['provider', '-is_default', '-is_active', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelconfiguration',
            options={'ordering': ['purpose'], 'verbose_name': '用途別モデル設定', 'verbose_name_plural': '用途別モデル設定'},
        ),
        migrations.RemoveField(
            model_name='modelconfiguration',
            name='model_name',
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='legacy_model_name',
            field=models.CharField(blank=True, help_text='レガシーモデル名（旧システムとの互換性用）', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='最大リトライ回数'),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.70'), help_text='Temperature（0.0-1.0）', max_digits=3),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='timeout_seconds',
            field=models.IntegerField(default=30, help_text='タイムアウト（秒）'),
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('other', 'その他')], help_text='AIプロバイダー', max_length=50)),
                ('model_id', models.CharField(help_text='モデルID（例: gpt-4o, claude-3-5-sonnet-20241022）', max_length=100)),
                ('display_name', models.CharField(help_text='表示名（例: GPT-4o（高性能））', max_length=200)),
                ('description', models.TextField(blank=True, help_text='モデルの説明', null=True)),
                ('context_window', models.IntegerField(blank=True, help_text='コンテキストウィンドウ（トークン数）', null=True)),
                ('max_output_tokens', models.IntegerField(blank=True, help_text='最大出力トークン数', null=True)),
                ('supports_streaming', models.BooleanField(default=True, help_text='ストリーミング対応')),
                ('supports_function_calling', models.BooleanField(default=False, help_text='関数呼び出し対応')),
                ('supports_vision', models.BooleanField(default=False, help_text='画像認識対応')),
                ('input_cost_per_1m', models.DecimalField(blank=True, decimal_places=4, help_text='入力コスト（USD/1Mトークン）', max_digits=10, null=True)),
                ('output_cost_per_1m', models.DecimalField(blank=True, decimal_places=4, help_text='出力コスト（USD/1Mトークン）', max_digits=10, null=True)),
                ('recommended_for_generation', models.BooleanField(default=False, help_text='SPIN質問生成に推奨')),
                ('recommended_for_chat', models.BooleanField(default=False, help_text='チャットに推奨')),
                ('recommended_for_scoring', models.BooleanField(default=False, help_text='スコアリングに推奨')),
                ('recommended_for_analysis', models.BooleanField(default=False, help_text='分析に推奨')),
                ('is_active', models.BooleanField(default=True, help_text='有効/無効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AIモデル',
                'verbose_name_plural': 'AIモデル',
                'ordering': ['provider', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='fallback_model',
            field=models.ForeignKey(blank=True, help_text='プライマリが失敗した場合の代替モデル', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_configs', to='spin.aimodel'),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='primary_model',
            field=models.ForeignKey(blank=True, help_text='メインで使用するモデル', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_configs', to='spin.aimodel'),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='fallback_provider_key',
            field=models.ForeignKey(blank=True, help_text='プライマリが失敗した場合の代替APIキー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_configs', to='spin.aiproviderkey'),
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='primary_provider_key',
            field=models.ForeignKey(blank=True, help_text='メインで使用するAPIキー', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_configs', to='spin.aiproviderkey'),
        ),
    ]
