# Generated by Django 5.2.8 on 2025-12-18 08:54

from django.db import migrations
from decimal import Decimal


def create_ai_models(apps, schema_editor):
    """AIモデルのマスターデータを作成"""
    AIModel = apps.get_model('spin', 'AIModel')
    
    # OpenAIモデル
    openai_models = [
        {
            'provider': 'openai',
            'model_id': 'gpt-5.2',
            'display_name': 'GPT-5.2（最新・最高性能・推論能力強化）',
            'context_window': 200000,
            'max_output_tokens': 16000,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': False,
            'input_cost_per_1m': Decimal('5.00'),
            'output_cost_per_1m': Decimal('15.00'),
            'recommended_for_generation': True,
            'recommended_for_scoring': True,
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-5.1',
            'display_name': 'GPT-5.1（高性能・推論能力）',
            'context_window': 200000,
            'max_output_tokens': 16000,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': False,
            'input_cost_per_1m': Decimal('3.00'),
            'output_cost_per_1m': Decimal('12.00'),
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-4o',
            'display_name': 'GPT-4o（高性能）',
            'context_window': 128000,
            'max_output_tokens': 16000,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('2.50'),
            'output_cost_per_1m': Decimal('10.00'),
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-4o-mini',
            'display_name': 'GPT-4o-mini（高速・低コスト）',
            'context_window': 128000,
            'max_output_tokens': 16000,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('0.15'),
            'output_cost_per_1m': Decimal('0.60'),
            'recommended_for_chat': True,
            'recommended_for_analysis': True,
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-4-turbo',
            'display_name': 'GPT-4 Turbo',
            'context_window': 128000,
            'max_output_tokens': 4096,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('10.00'),
            'output_cost_per_1m': Decimal('30.00'),
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-4',
            'display_name': 'GPT-4',
            'context_window': 8192,
            'max_output_tokens': 8192,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': False,
            'input_cost_per_1m': Decimal('30.00'),
            'output_cost_per_1m': Decimal('60.00'),
        },
        {
            'provider': 'openai',
            'model_id': 'gpt-3.5-turbo',
            'display_name': 'GPT-3.5 Turbo（レガシー）',
            'context_window': 16385,
            'max_output_tokens': 4096,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': False,
            'input_cost_per_1m': Decimal('0.50'),
            'output_cost_per_1m': Decimal('1.50'),
        },
    ]
    
    # Anthropic (Claude) モデル
    anthropic_models = [
        {
            'provider': 'anthropic',
            'model_id': 'claude-3-5-sonnet-20241022',
            'display_name': 'Claude 3.5 Sonnet（最新）',
            'context_window': 200000,
            'max_output_tokens': 8192,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('3.00'),
            'output_cost_per_1m': Decimal('15.00'),
            'recommended_for_scoring': True,
        },
        {
            'provider': 'anthropic',
            'model_id': 'claude-3-opus-20240229',
            'display_name': 'Claude 3 Opus',
            'context_window': 200000,
            'max_output_tokens': 4096,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('15.00'),
            'output_cost_per_1m': Decimal('75.00'),
        },
        {
            'provider': 'anthropic',
            'model_id': 'claude-3-haiku-20240307',
            'display_name': 'Claude 3 Haiku（高速・低コスト）',
            'context_window': 200000,
            'max_output_tokens': 4096,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('0.25'),
            'output_cost_per_1m': Decimal('1.25'),
            'recommended_for_chat': True,
        },
    ]
    
    # Google (Gemini) モデル
    google_models = [
        {
            'provider': 'google',
            'model_id': 'gemini-1.5-pro',
            'display_name': 'Gemini 1.5 Pro',
            'context_window': 2000000,
            'max_output_tokens': 8192,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('1.25'),
            'output_cost_per_1m': Decimal('5.00'),
        },
        {
            'provider': 'google',
            'model_id': 'gemini-1.5-flash',
            'display_name': 'Gemini 1.5 Flash（高速・低コスト）',
            'context_window': 1000000,
            'max_output_tokens': 8192,
            'supports_streaming': True,
            'supports_function_calling': True,
            'supports_vision': True,
            'input_cost_per_1m': Decimal('0.075'),
            'output_cost_per_1m': Decimal('0.30'),
            'recommended_for_chat': True,
            'recommended_for_analysis': True,
        },
    ]
    
    # 全てのモデルを作成
    for model_data in openai_models + anthropic_models + google_models:
        AIModel.objects.get_or_create(
            provider=model_data['provider'],
            model_id=model_data['model_id'],
            defaults=model_data
        )


def migrate_openai_api_keys(apps, schema_editor):
    """既存のOpenAIAPIKeyデータを新しいAIProviderKeyに移行"""
    OpenAIAPIKey = apps.get_model('spin', 'OpenAIAPIKey')
    AIProviderKey = apps.get_model('spin', 'AIProviderKey')
    
    # 既存のOpenAIAPIKeyを全て取得
    for old_key in OpenAIAPIKey.objects.all():
        # 新しいAIProviderKeyを作成
        AIProviderKey.objects.create(
            id=old_key.id,  # UUIDを維持
            name=old_key.name,
            provider='openai',  # OpenAIとして設定
            api_key=old_key.api_key,
            description=old_key.description or f"用途: {old_key.get_purpose_display()}, モデル: {old_key.model_name}",
            is_active=old_key.is_active,
            is_default=old_key.is_default,
            created_at=old_key.created_at,
            updated_at=old_key.updated_at,
        )


def migrate_model_configurations(apps, schema_editor):
    """既存のModelConfigurationを新しい構造に移行"""
    ModelConfiguration = apps.get_model('spin', 'ModelConfiguration')
    AIProviderKey = apps.get_model('spin', 'AIProviderKey')
    AIModel = apps.get_model('spin', 'AIModel')
    
    # デフォルトのOpenAI APIキーを取得
    default_provider_key = AIProviderKey.objects.filter(
        provider='openai',
        is_active=True
    ).first()
    
    if not default_provider_key:
        # APIキーがない場合は何もしない
        return
    
    # 既存の設定を更新
    for config in ModelConfiguration.objects.all():
        # レガシーモデル名がない場合はスキップ
        if not hasattr(config, 'model_name'):
            continue
        
        # 旧model_nameを保存（まだ削除されていない場合）
        try:
            old_model_name = config.model_name
            config.legacy_model_name = old_model_name
        except:
            pass
        
        # 対応するAIModelを検索
        try:
            ai_model = AIModel.objects.get(
                provider='openai',
                model_id=config.legacy_model_name
            )
            config.primary_provider_key = default_provider_key
            config.primary_model = ai_model
            config.save()
        except AIModel.DoesNotExist:
            # モデルが見つからない場合はスキップ
            pass


def reverse_migration(apps, schema_editor):
    """ロールバック用（必要に応じて実装）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0014_aiproviderkey_alter_modelconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_ai_models, reverse_migration),
        migrations.RunPython(migrate_openai_api_keys, reverse_migration),
        migrations.RunPython(migrate_model_configurations, reverse_migration),
    ]
