# Generated by Django 5.2.8 on 2025-12-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0015_migrate_to_multi_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderkey',
            options={'ordering': ['provider', '-is_default', '-is_active', '-created_at'], 'verbose_name': 'API統合管理', 'verbose_name_plural': 'API統合管理'},
        ),
    ]
