# Generated by Django 5.2.9 on 2025-12-23 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0017_emailverificationtoken_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='メールアドレス', max_length=254)),
                ('is_verification_email', models.BooleanField(default=False, help_text='ログイン認証メール送信用に使用するメールアドレス（1ユーザーに1つまで）')),
                ('verified', models.BooleanField(default=False, help_text='メールアドレスの認証状況')),
                ('verified_at', models.DateTimeField(blank=True, help_text='認証完了日時', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザーメールアドレス',
                'verbose_name_plural': 'ユーザーメールアドレス',
                'ordering': ['-is_verification_email', 'created_at'],
                'unique_together': {('user', 'email')},
            },
        ),
    ]
