# Generated by Django 5.2.9 on 2025-12-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0019_systememailaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemEmailAddress',
        ),
    ]
