# Generated by Django 5.2.9 on 2025-12-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0020_delete_systememailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('real_estate', '不動産（売買・賃貸）'), ('insurance', '保険（生保・損保）'), ('it_saas', 'IT・SaaS'), ('hr', '人材（派遣・紹介）'), ('advertising', '広告・マーケティング'), ('automotive', '自動車（販売・リース）'), ('finance', '金融（銀行・証券）'), ('manufacturing', '製造業'), ('retail', '小売・EC'), ('telecom', '通信'), ('other', 'その他')], help_text='業種', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sales_experience',
            field=models.CharField(blank=True, choices=[('less_than_1', '1年未満'), ('1_to_3', '1〜3年'), ('3_to_5', '3〜5年'), ('5_plus', '5年以上')], help_text='営業経験年数', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usage_purpose',
            field=models.CharField(blank=True, choices=[('improve_skills', '商談スキルを向上させたい'), ('proposal', '提案力を強化したい'), ('questioning', '質問力を磨きたい'), ('interview', '面接・転職対策'), ('team_training', 'チームの育成に使いたい'), ('other', 'その他')], help_text='利用目的', max_length=50, null=True),
        ),
    ]
