# Generated by Django 5.2.9 on 2025-12-26 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0021_userprofile_industry_userprofile_sales_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(help_text='ハッシュ化されたパスワード', max_length=128)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_experience', models.CharField(blank=True, max_length=20, null=True)),
                ('usage_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='トークンの有効期限')),
                ('verified', models.BooleanField(default=False, help_text='メール認証完了フラグ')),
                ('verified_at', models.DateTimeField(blank=True, help_text='認証完了日時', null=True)),
            ],
            options={
                'verbose_name': '仮登録ユーザー',
                'verbose_name_plural': '仮登録ユーザー',
                'ordering': ['-created_at'],
            },
        ),
    ]
