# Generated by Django 5.2.9 on 2025-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0022_pendinguserregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='realtime_mode',
            field=models.BooleanField(default=False, help_text='リアルタイム音声会話モード'),
        ),
    ]
